name: Terraform CI CD

on:
    workflow_dispatch:
    push:
        branches:
            - main
    pull_request:

jobs: 
    terraform:
        name: Terraform Deploy
        runs-on: ubuntu-latest

        permissions:
          id-token: write
          contents: read

        steps: 
            # Step 1: Checkout the Code to Repository
            - name: Checkout Code
              uses: actions/checkout@v3

            # Step 2: Setup Terraform
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2
              with: 
                terraform_version: 1.5.0

            # Step 3: Configure AWS Credentials
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v3
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}
                
            # Step 4: Initialize Terraform
            - name: Terraform Init
              run: terraform init

            # Step 5: Terraform Plan
            - name: Terraform Plan
              run: terraform plan
            #  run: terraform plan -var-file=terraform.tfvars

            # Step 6: Terraform Apply
            - name: Terraform Apply
              if: github.event_name == 'push' && github.ref == 'refs/heads/main'
              run: terraform apply -auto-approve tfplan