name: Terraform EC2 Deployment

on:
    workflow_dispatch:
    push:
        branches:
            - main
    pull_request:

jobs: 
    terraform:
        name: Terraform Apply
        runs-on: ubuntu-latest

        steps: 
            # Step 1: Checkout the Code
            - name: Checkout Code
              uses: actions/checkout@v3

            # Step 2: Setup Terraform
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2
              with: 
                terraform_version: 1.5.0
                
            # Step 3: Initialize Terraform
            - name: Terraform Init
              run: terraform init

            # Step 4: Terraform Plan
            - name: Terraform Plan
              run: terraform plan -var-file=terraform.tfvars

            # Step 5: Terraform Apply
            - name: Terraform Apply
              run: terraform apply -var-file=terraform.tfvars -auto-approve
              env: 
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
